# Site info
title: FEMUG-CWB
description: "Seja bem-vindo ao FEMUG-CWB, projeto para unir os desenvolvedores Front-End de Curitiba!"
url: http://femug-cwb.com.br
favicon: /images/favicon.ico
# google-analytics: "UA-70860926-1"
email: femug.cwb@gmail.com
twitter: femugcwb

source: source
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded