# Site info
title: FEMUG-CWB
url: http://femug-cwb.com.br
favicon: /images/favicon.ico
google-analytics: "UA-70860926-1"
email: femug.cwb@gmail.com
twitter: femugcwb

# Active sections on the website
sections:
  - slug: about
    title: Sobre
  - slug: location
    title: Localização
  - slug: speakers
    title: Palestrantes
  - slug: schedule
    title: Cronograma
  # - slug: sponsors
  #   title: Patrocinadores
  #- slug: partners
  #  title: Parceiros
  - slug: contact
    title: Contato

source: source
sass:
  sass_dir: _sass
  style: compressed